In [1]:
import pandas as pd

In [7]:
retials_data= pd.read_csv('Demo_Retail_Dataset.csv')

In [8]:
print(retials_data.shape)

(541909, 8)

In [10]:
print(list(retials_data.columns))

['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [12]:
retials_data.head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom

# cleaning data for usage

# we will remove all the null values columns

In [16]:
retials_data.dropna(inplace=True)

In [18]:
retials_data.isna

<bound method DataFrame.isna of        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

                InvoiceDate  UnitPrice  CustomerID         Country
0       2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1       2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2       2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3       2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4       2010-12-01 08:26:00       3.39     17850.0  United Kingdom
...                     ...        ...         ...             ...
541904  2011-12-09 12:50:00       0.85     12680.0          France
541905  2011-12-09 12:50:00       2.10     12680.0          France
541906  2011-12-09 12:50:00       4.15     12680.0          France
541907  2011-12-09 12:50:00       4.15     12680.0          France
541908  2011-12-09 12:50:00       4.95     12680.0          France

[406829 rows x 8 columns]>

In [21]:
# Make the customer ID a string instead of being an integer 
retials_data['CustomerID']= retials_data['CustomerID'].apply(lambda X:'C'+str(int(X)))

In [23]:
retials_data.head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,C17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,C17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,C17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,C17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,C17850,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,C17850,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,C17850,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,C17850,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,C17850,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,C13047,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,C13047,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,C13047,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,C13047,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,C13047,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,C13047,United Kingdom

In [35]:
orders= retials_data[['CustomerID', 'Description', 'InvoiceNo', 'Quantity']]

In [36]:
orders.head(10)

  CustomerID                          Description InvoiceNo  Quantity
0     C17850   WHITE HANGING HEART T-LIGHT HOLDER    536365         6
1     C17850                  WHITE METAL LANTERN    536365         6
2     C17850       CREAM CUPID HEARTS COAT HANGER    536365         8
3     C17850  KNITTED UNION FLAG HOT WATER BOTTLE    536365         6
4     C17850       RED WOOLLY HOTTIE WHITE HEART.    536365         6
5     C17850         SET 7 BABUSHKA NESTING BOXES    536365         2
6     C17850    GLASS STAR FROSTED T-LIGHT HOLDER    536365         6
7     C17850               HAND WARMER UNION JACK    536366         6
8     C17850            HAND WARMER RED POLKA DOT    536366         6
9     C13047        ASSORTED COLOUR BIRD ORNAMENT    536367        32

In [69]:
# Drop descriptions which are not uppercase
orders= orders[orders['Description'].str.upper()==orders['Description']
                          ]

In [70]:
orders.head(10)

  CustomerID                          Description InvoiceNo  Quantity
0     C17850   WHITE HANGING HEART T-LIGHT HOLDER    536365         6
1     C17850                  WHITE METAL LANTERN    536365         6
2     C17850       CREAM CUPID HEARTS COAT HANGER    536365         8
3     C17850  KNITTED UNION FLAG HOT WATER BOTTLE    536365         6
4     C17850       RED WOOLLY HOTTIE WHITE HEART.    536365         6
5     C17850         SET 7 BABUSHKA NESTING BOXES    536365         2
6     C17850    GLASS STAR FROSTED T-LIGHT HOLDER    536365         6
7     C17850               HAND WARMER UNION JACK    536366         6
8     C17850            HAND WARMER RED POLKA DOT    536366         6
9     C13047        ASSORTED COLOUR BIRD ORNAMENT    536367        32

In [71]:
# non-peronalized recommandations
#print out the number of orders that are made in each product 
numbers_orders_perProduct= orders.groupby('Description').agg(orders=('InvoiceNo', 'nunique'), 
                                                                   ).sort_values(by='orders', ascending=False).head(10)

In [72]:
numbers_orders_perProduct

                                    orders
Description
WHITE HANGING HEART T-LIGHT HOLDER    2013
REGENCY CAKESTAND 3 TIER              1884
JUMBO BAG RED RETROSPOT               1643
PARTY BUNTING                         1399
ASSORTED COLOUR BIRD ORNAMENT         1385
LUNCH BAG RED RETROSPOT               1329
SET OF 3 CAKE TINS PANTRY DESIGN      1218
POSTAGE                               1194
LUNCH BAG  BLACK SKULL.               1073
PACK OF 72 RETROSPOT CAKE CASES       1041

In [73]:

# print out quantity  of items sold in each product 
quantity_each_sold= orders.groupby('Description').agg(quantity=('Quantity', 'sum')
).sort_values(by='quantity', ascending=False).head(10)

In [74]:
quantity_each_sold

                                    quantity
Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS      53215
JUMBO BAG RED RETROSPOT                45066
ASSORTED COLOUR BIRD ORNAMENT          35314
WHITE HANGING HEART T-LIGHT HOLDER     34147
PACK OF 72 RETROSPOT CAKE CASES        33409
POPCORN HOLDER                         30504
RABBIT NIGHT LIGHT                     27094
MINI PAINT SET VINTAGE                 25880
PACK OF 12 LONDON TISSUES              25321
PACK OF 60 PINK PAISLEY CAKE CASES     24163

In [75]:
# create user item interaction with our data 
int_matrix= orders.pivot_table(index='CustomerID', columns=['Description'], values='Quantity', fill_value=0.0)
int_matrix.head(10)

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
CustomerID,,,,,,,,,,,,,,,,,,,,,
C12346,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12347,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12348,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12349,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12350,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12352,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12353,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12354,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12355,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0
C12356,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0.0,0,0.0,0,0.0

In [76]:
# user based remmended system 
active_user= 'C12347'
recommendations= int_matrix.corrwith(int_matrix.loc[active_user], axis=1)
recommendations.dropna(inplace=True)
recommendations

CustomerID
C12347    1.000000
C12348    0.163545
C12349    0.005202
C12350    0.015139
C12352    0.004437
            ...
C18280    0.007461
C18281   -0.003102
C18282    0.010109
C18283    0.019187
C18287    0.101071
Length: 4350, dtype: float64

In [77]:
# Create DataFram from the corelletion between users
recommandations= pd.DataFrame(recommendations, columns=['Correlation']).reset_index()
recommandations = recommandations.sort_values(by='Correlation', ascending=False)
recommandations.head(10)

     CustomerID  Correlation
0        C12347     1.000000
1455     C14326     0.779165
7        C12355     0.710882
1410     C14257     0.620565
889      C13532     0.572588
2607     C15882     0.521028
2350     C15539     0.520732
2243     C15396     0.520150
2107     C15215     0.515967
4043     C17866     0.504141

In [87]:
# find the items that is used the similar user but not the active user
active_user= 'C12347'
similar_user= 'C14326'
for item, quantity in int_matrix.loc[similar_user].items():
    if quantity > 0 and int_matrix.loc[active_user][item]==0:
        print("Name of the item:  {}".format(item)) 
        print("Quantity purchesed by similar user: {}".format(quantity))
        print("Quantity purchesed by active user: {}".format(int_matrix.loc[active_user][item]))

Name of the item:  ANTIQUE SILVER T-LIGHT GLASS
Quantity purchesed by similar user: 12.0
Quantity purchesed by active user: 0.0
Name of the item:  ENAMEL FLOWER JUG CREAM
Quantity purchesed by similar user: 3.0
Quantity purchesed by active user: 0.0
Name of the item:  FELTCRAFT 6 FLOWER FRIENDS
Quantity purchesed by similar user: 12.0
Quantity purchesed by active user: 0.0
Name of the item:  GROW YOUR OWN BASIL IN ENAMEL MUG
Quantity purchesed by similar user: 8.0
Quantity purchesed by active user: 0.0
Name of the item:  HANGING HEART JAR T-LIGHT HOLDER
Quantity purchesed by similar user: 12.0
Quantity purchesed by active user: 0.0
Name of the item:  SET/3 OCEAN SCENT CANDLE JEWEL BOX
Quantity purchesed by similar user: 4.0
Quantity purchesed by active user: 0.0

# ITEM-BASED COLLABROATIVE FILTERING

In [98]:
item= "WHITE HANGING HEART T-LIGHT HOLDER"
recommendations= int_matrix.corrwith(int_matrix[item])
recommendations.dropna(inplace=True)
recommandations= pd.DataFrame(recommendations, columns=['Correlation']).reset_index()
recommandations = recommandations.sort_values(by='Correlation', ascending=False)
recommandations.head(10)

                             Description  Correlation
3680  WHITE HANGING HEART T-LIGHT HOLDER     1.000000
1378         GIN + TONIC DIET METAL SIGN     0.704755
3404                TEA TIME TEA TOWELS      0.650505
1153  FAIRY CAKE FLANNEL ASSORTED COLOUR     0.593688
2679    RED HANGING HEART T-LIGHT HOLDER     0.530743
1006                  DOORMAT FAIRY CAKE     0.515547
2177              OPEN CLOSED METAL SIGN     0.476353
2784    RETROSPOT HEART HOT WATER BOTTLE     0.476083
2388               PIGGY BANK RETROSPOT      0.476052
333             BLACK AND WHITE CAT BOWL     0.473697